# Generated by Django 4.1.7 on 2023-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created_at'], name='images_uplo_created_70d92d_idx'),
        ),
    ]
