# Generated by Django 4.1.7 on 2023-02-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0002_alter_image_options_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='author',
            new_name='user',
        ),
    ]
