# Generated by Django 4.1.7 on 2023-02-21 20:44

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0003_rename_img_image_image_rename_author_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_test_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=thumbnails.fields.ImageField(upload_to='images/'),
        ),
    ]
