# Generated by Django 4.1.7 on 2023-02-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_upload', '0004_image_img_test_url_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_test_url',
        ),
    ]
